# Add label hgcreation when a file with extension .hg, .info, .md is created inside a subfolder
hgcreation:
- base-branch: 'main'
- changed-files:
  - all-globs-to-all-file: ['**/**/.md', '**/**/.hg', '**/**/.info']
  - all-globs-to-all-files: '!scripts/*'

info:
- README.md