# Add label hgcreation when a file with extension .hg, .info, .md is created inside a subfolder
hgcreation:
- base-branch: 'main'
- changed-files:
  - any-glob-to-any-file: '**/**/.hg'
  - any-glob-to-any-file: '**/**/.info'
  - all-globs-to-all-files: '!scripts/*'

infoRepo:
- base-branch: 'main'
- changed-files:
  - any-glob-to-any-file: 'README.md'