name: PR Contains

on:
  pull_request:
    branches: [main]

env:
  PR_NUMBER: ${{ github.event.number }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      template: ${{ steps.step1.outputs.template }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: 'pip'
      - run: pip install -r ./scripts/requirements.txt

      - name: Run PR Contains
        id: step1
        run: |
          python -u ./scripts/pr_contains.py

  job1:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: echoResult
        run: |
          echo ${{needs.build.outputs.template}} 

# OUTPUT1:
